@startuml
left to right direction
skinparam packageStyle rectangle
actor &quot;Пациент&quot; as User
package &quot;Система&quot; {
usecase &quot;Вход в систему&quot; as UC_Login
usecase &quot;Бронирование сеанса с врачом&quot; as UC_Bron'
usecase &quot;Просмотр расписания&quot; as UC_Rasp
}
left to right direction
skinparam packageStyle rectangle
actor &quot;Администратор&quot; as User
package &quot;Система&quot; {
usecase &quot;Вход в систему&quot; as UC_Login
usecase &quot;Создание профиля пациента / врача&quot; as UC_Create
usecase &quot;Просмотр расписания&quot; as UC_Rasp
usecase &quot;Редактирование расписания&quot; as UC_Redact
}
left to right direction
skinparam packageStyle rectangle
actor &quot;Врач&quot; as User
package &quot;Система&quot; {
usecase &quot;Вход в систему&quot; as UC_Login
usecase &quot;Просмотр расписания&quot; as UC_Rasp
}
User --&gt; UC_Login
User --&gt; UC_Rasp
User --&gt; UC_Bron'
User --&gt; UC_Redact
User --&gt; UC_Create
@enduml